### ISSUE TITLE
CRUD Users

### ISSUE THREAD

**Issue by iuresti** [desarrolladorSLP/technovationslp-management-app#2]
Users must have:
* Name
* email
* phone number

** Add mockup for screen(s) for CRUD operations

**Comment by AntonioVarela** [comment]
https://drive.google.com/drive/folders/1rp5ZpBHmxQNpzx-5kKV-ADgO7sm5ugmM?usp=sharing[](url)

![CRUD](https://user-images.githubusercontent.com/25315387/61647620-58a5fb00-ac73-11e9-8520-a89aac88e6f8.png)

![Login](https://user-images.githubusercontent.com/25315387/61647622-593e9180-ac73-11e9-94b8-930fe8cb1908.png)

![Register](https://user-images.githubusercontent.com/25315387/61647624-593e9180-ac73-11e9-9e7b-9791df70a393.png)

**Comment by iuresti** [comment]
Closing this issue as Active and Inactive users screen cover what is needed
